[package]
name = "rust_line_bot_sdk"
version = "0.1.0"
authors = ["Supanat Pothivarakorn <supanat.ptk@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "0.7"
serde = "1.0"
serde_derive = "1.0"
serde_json = { version = "1.0",  features = ["arbitrary_precision"] }
reqwest = "0.9.5"
